### ISSUE TITLE
Discussion: Possible Alternate Method Draw backend

### ISSUE THREAD

**Issue by techninja** [duopixel/Method-Draw#37]
I've been using a slightly modified version of Method-Draw in my application "[RoboPaint](https://github.com/evil-mad/robopaint)" for nearly 3 years now as a way to create/edit/import/clean SVGs for painting with robots. Though It's vastly better than the likely now defunkt SVG-Edit project, it's far from perfect, and the project owners can likely not keep up with the issues.

It's been the best of times, it's been the worst of times. ;)

There have always things that work well and look great (the interface), and then things that are mostly unreliable or act very strangely (simple path shape bounds, unsimplified pencil path creation, random path position resets), and it's no wonder: The SVG standard is huge and complicated, and this work is based off of a giant legacy codebase with thousands of lines of code written while web standards they applied to kept changing.

#### My proposal:
A fork, of sorts. I've done [a little research](https://github.com/evil-mad/robopaint/issues/223) into [Paper.js](http://paperjs.org), an incredible "Swiss Army Knife of Vector Graphics Scripting.". On the outset, it seems like a perfect fit to _systematically replace the flawed inner workings_ from SVG-Edit. 

So says the readme: 
 > The purpose of Method Draw is to improve the usability and user experience of SVG Edit.

And I think the project has done that in spades. It's clean, efficient, and nice to use, if only things _actually worked_ as they were expected to every time. I've personally found that creating tools and user interface for use with Paper.js is a breeze, and in theory, it's perfectly possible to recreate the exact look of Method-Draw, simply powered by a well tested, well supported back-end with some pretty impressive capabilities beyond SVG-edit.

I can't do this alone, or without some kind of support. At this point I'm simply looking for feedback, or interest from the communities that could be involved. Thanks for reading.

**Comment by rodrigoaguilera** [comment]
The proposal sounds very good. Just to clarify that SVG-edit is not completely dead 
https://github.com/SVG-Edit/svgedit

**Comment by techninja** [comment]
Good to hear it's not completely gone, though I'd imagine getting its changes pushed back into method-draw would be a pretty high ask. Comparable in effort to this propsal, and likely not in the direction of a simpler to manage codebase :/

**Comment by duopixel** [comment]
I have no plans to keep on developing Method Draw other than putting bits of work here and there, so any alternative is welcome. Part of the reason why both Method Draw and SVG Edit have both stagnated is because the codebase is painful to work in. There's plenty of talent behind the code of SVG Edit, but it comes from a time when javascript best coding practices weren't very well defined.

Unfortunately the project why I started Method Draw in the first place is dead, so I have no excuse to put in more time into this. I would very much rally behind any other alternative, but from what I've seen little has materialized. There's not much I can do except offer words of encouragement and—if something becomes real—to offer design expertise as time allows (I'm a designer who accidentally fell into front-end coding).

Best of luck!

**Comment by nicholaswmin** [comment]
@techninja 

Unfortunately Paper.js is plagued by the all too common issue that all vector-emulating Canvas libraries suffer from.

The redraw/repaint cycle is handled in Javascript and it's hardly optimized to say the least. Thus they tend to slow down to a halt when high-node elements are designed.

SVG redraw cycles are handled natively by the browser and there seems to be some optimisation work done by the browsers vendors. E.g only parts of the scene that have changed are redrawed.

Personally, I'd be very disappointed if the only decent SVG editor(Method-Draw) was re-implemented using Paper.js.

**Comment by techninja** [comment]
I've seen the redraw issue first hand with large graphics with thousands of paths like stippled images.

> **Why not base it on SVG?**
>
> We have decided to use the Canvas object as the main backend because in our initial testing it was faster than SVG and allowed us to implement, optimize and have full control over our own Scene Graph / Document Object Model. SVG import / export is available and well tested...

I generally suspect some of that may be a different now, and likely in the future Paper might be able to decouple some of its API into something that could output/control actual DOM objects directly in SVG, though I'm not at all sure if that's on @lehni's radar or gameplan. Though I believe that performance has always been something they've been working through and looking to improve, I'm just not sure if it's a losing battle without being lower level.

FWIW no work has been done toward this end. I am far too busy trying to keep a roof over my head to chase this wild goose that not everyone can actually agree is entirely worth chasing, at least the discussion has bore fruit worth talking about.

**Comment by nicholaswmin** [comment]
So off the top of my head (this is just guessing).

- The Paper folks didn't evaluate the Canvas vs SVG perf battle, based on an interactivity-based model. It's faster to just draw a circle-like element on Canvas since we just draw it's pixels. SVG creates a whole DOM element. Moving items around however, especially against a populated scene is a different story however and this is where repaint optimisations shine. This is a point that can be answered by Jurg.

- SVG might have gotten more optimised as time went by.

Again, the above are just suspicions on my part. 

====

There was for a very long time now a plan to implement an alternative SVG backend in Paper.js. It was discussed numerous times and from what I've seen in the source code of Paper, it is fairly simple to do so since the classes are decoupled from the draw operations. It's theoretically simple, but I'd guess that in practise it's a lot of work. (Keep in mind that the current API can't change that much and there would be inconsistencies between what Canvas can do and how it does it vs an SVG backend).

I hate to play devils advocate instead of actually getting on with the work but all the Canvas libraries are disappointing in terms of performance( you know this as well from first-hand experience). I have also seen and researched the subject numerous times before.

> Though I believe that performance has always been something they've been working through and looking to improve, I'm just not sure if it's a losing battle without being lower level.

There was never much effort being put into making Paper.js fast. While the code standards, code structure and code elegance, are what I consider to be top-level and while there were numerous discussions and ideas about improving performance, there are no significant implementations of code regarding time-shaving off the redraw cycles. 

I would have done the same thing if I was them. They focused on the "logic/algorithms" of the library with the hopes that the drawing performance issues would be solved by switching to an SVG backend. In other words, why duplicate optimisation work that was already being done by the browser vendors? 

Anyway, I'd say that all these points/speculations I've made might belong in the Paper.js discussions instead of Method-Draw but maybe they help the discussion, I'm not sure.

**Comment by lehni** [comment]
The assumptions by @nicholaswmin here are pretty accurate for the most part. We have put a fair amount of effort into optimizing drawing on the canvas, without going the extra mile of implementing a mechanism that keeps track of 'dirty' areas that need redrawing, or cache parts of the scene graph that haven't changed. There is some work in place for this, e.g. we calculate and cache bounding boxes of the whole scene graph very fast and accurately. I was weary so far of implementing this further though, because of the complexity it adds to the framework, as well as the potential upcoming adding of a SVG backend, which would mean that energy could be spent more wisely there.

But be aware that adding SVG won't just magically solve all the issues. We are aware of many situations, especially with animation, where the canvas beats SVG hands down. The involvement of the DOM leads to all kind of weirdness and potential slow downs in other areas, there are incompatibilities between implementations and browsers, etc. And I have yet to implement all the ideas for performance improvements in cavnas.

And there are some good reasons to believe that there is still a lot of room for improvement with canvas. Have you looked at http://gravit.io/? It's a very capable online vector editor that is buit solely in canvas, ditching SVG alltogether. And it appears to achieve very good performance, just by using rendering caching of the parts that don't change. We can certainly do the same in paper.js, still, and should do so regardless of the SVG plans.

But then there is also the need for better support of typography, and without wanting to implement all the details of that (writing a proper Unicode layout engine with support for all different scripts is definitely taking it too far), SVG is the only decent way to get that in place, including editability. 

But we can't solely rely on SVG because we also offer a version running in Node, based on node-canvas, and I'm not aware of any node-svg rendering libraries... And any future branching there will add huge complexity.

And when I say 'we', it is unfortunately mainly me these days, but luckily along with a group of great contributors that work on various specific aspects of the library, e.g. @hkrish and @iconexperience, who have put a huge amount of work and effort into the boolean operations code. If anybody wants to join the effort and put work into such a backend, I am more than happy to outline the current ideas and oversee the work.

And I would love to find more time to put into optimizing paper.js and finally working on that SVG backend to removing that potential bottle neck, but that's just one of many construction sites we currently have, another one being the boolean operations that still struggle in some crazy edge cases (but we've come a very very long way here), path offsetting and stroke expansion (nearly done), a better mouse event model, typography, etc, and more often than not I haven't found enough time to work on the framework lately, due to my many other engagements that actually pay the bills.

In the past discussions about such feature requests I've always pointed out that if a feature or change is important to a project or business, I'd be very happy for the work on it to be sponsored and hence prioritized. Until this doesn't happen, I treat paper.js as a spare-time project where I work on the parts of the framework that I am most excited to be working on. And SVG is unfortunately not one of those areas at the moment, it just seems like a whole lot of trouble to get it done.

**Comment by nicholaswmin** [comment]
:+1: 

Unless someone is up for tackling the SVG backend himself, I think Jurg's answer pretty much concludes the question.

**Comment by techninja** [comment]
Completely agree with you both, but I can't help but feel that the issue of drawing efficiency doesn't completely close the issue at hand. It's certainly a problem for some art, but not _ALL_ art, and unless all you do is deal with these edge cases, it's likely still to be a better and stronger base than SVG-Edit has been. Certainly for most use cases in our given user base Paper.js could perform beautifully and with basically no user experience change (in theory).

Again, this is all moot as I've seen no monetary backed interest in this (nor much interest in the call for devs originally), and it's likely the problems within Method-Draw are not insurmountable, though still tricky to keep up with. If anything this has been a good soapbox for discussion and can be closed to tidy this up. If anyone wants to follow the rabbit hole, further discussion should be found/sent here: https://github.com/techninja/Paper-Draw/issues/1

**Comment by lehni** [comment]
What I am a bit confused by, and apologies if I'm blunt: RobotPaint is at the core of the WaterColorBot, which ran a very successful Kickstarter campaign (congrats on that!), yet you state repeatedly that there is no monetary backed interest in this endeavor.

**Comment by lehni** [comment]
Another source of confusion: I've expressed my interest in working on a [project like this](https://groups.google.com/d/msg/paperjs/4u5JHd3mpw8/-1YQhv2cEwAJ) before, but the discussion just died off after that. Then I discover months later that you started three discussions in different places on GitHub about the idea, and mentioned my interest in one of them... But let the discussion on the paper.js mailing list lead nowhere. And this discussion here I only became aware of because you mentioned me with my handle 6 days ago, for the first time ever.
